## MinIO Deployment Configuration using Bitnami Chart (without TLS)

# 1. MinIO Access Credentials
auth:
  rootUser: admin
  rootPassword: adminadmin

# 2. Deployment Configuration
mode: standalone
replicaCount: 1

# 3. Persistence (Data Storage)
persistence:
  enabled: true
  existingClaim: ""
  size: 10Gi
  storageClass: "local-path"
  accessModes:
    - ReadWriteOnce
  mountPath: /bitnami/minio/data

# 4. Service Configuration
service:
  type: ClusterIP
  ports:
    api: 9000
    console: 9001

# 5. Console Service
consoleService:
  enabled: true
  type: ClusterIP
  port: 9001

# 6. Ingress Configuration (No TLS)
ingress:
  enabled: true
  hostname: minio.virtual33.myguest.virtualbox.org
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "false"  # Explicitly disabling TLS
  tls: []  # No TLS configuration
  extraPaths: []
  pathType: Prefix
  path: /

# 7. Extra Environment Variables (Optional)
extraEnvVars:
  - name: MINIO_BROWSER_REDIRECT_URL
    value: "http://minio.virtual33.myguest.virtualbox.org"

# 8. Network Policy (Optional)
networkPolicy:
  enabled: false

