apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: quay.io/strimzi/kafka:0.35.0-kafka-3.4.0
          command: ["sh", "-c", "bin/kafka-server-start.sh /tmp/kafka/strimzi.properties"]
          ports:
            - containerPort: 9092
            - containerPort: 9097
          env:
            - name: LOG_DIR
              value: "/tmp/logs"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-0.zookeeper.opa.svc.cluster.local:2181"
          volumeMounts:
            - name: kafka-config
              mountPath: /tmp/kafka/
      volumes:
        - name: kafka-config
          configMap:
            name: kafka-config
