apiVersion: v1
kind: ConfigMap
metadata:
  name: ngw-config
data:
  application.yaml: |
    server:
      port: 9090
    spring:
      cloud:
        gateway:
          httpclient:
            ssl:
              useInsecureTrustManager: true
            wiretap: true
          httpserver:
            wiretap: true
          routes:
          - id: A1-EI2
            uri: http://ics:8083
            predicates:
            - Path=/data-producer/**,/data-consumer/**
    management:
      endpoint:
        gateway:
          enabled: true
      endpoints:
        web:
          exposure:
            include: "gateway,loggers,logfile,health,info,metrics,threaddump,heapdump"
    logging:
      level:
        ROOT: ERROR
        org.springframework: ERROR
        org.springframework.cloud.gateway: INFO
        reactor.netty: INFO
      file:
        name: /var/log/nonrtric-gateway/application.log

