apiVersion: v1
kind: Service
metadata:
  name: nonrtric-gateway
spec:
  selector:
    app: nonrtric-gateway
  ports:
    - protocol: TCP
      port: 9098
      targetPort: 9090
  type: ClusterIP  # Change to NodePort or LoadBalancer if external access is needed

