apiVersion: v1
kind: Service
metadata:
  name: ics
spec:
  selector:
    app: ics
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
    - protocol: TCP
      port: 8434
      targetPort: 8434
  type: ClusterIP  # Change to NodePort or LoadBalancer if external access is needed

