apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181  # Port exposed in Kubernetes
      targetPort: 2181  # Port inside the container
  clusterIP: None  # Headless service for Kafka discovery

